{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "kPbjREmzMIST"
      },
      "source": [
        "# Portfólio Fullstack - Capacita BR\n",
        "\n",
        "## O que é o projeto  🚀\n",
        "\n",
        "Este repositório contém o projeto final do módulo basico de Desenvolvimento Fullstack do programa Capacita BR.\n",
        "O objetivo é apresentar um portfólio em grupo com as principais habilidades adquiridas durante esse primeiro modulo do curso, aplicando os conhecimentos em: **HTML**, **CSS** e **GIT/GitHub**.\n",
        "\n",
        "<p align=\"center\">\n",
        "  <a href=\"https://devicon.dev/\">\n",
        "    <img src=\"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg\" width=\"50\" />\n",
        "  </a>\n",
        "  <a href=\"https://devicon.dev/\">\n",
        "    <img src=\"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg\" width=\"50\" />\n",
        "  </a>\n",
        "  <a href=\"https://devicon.dev/\">\n",
        "  <img src=\"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg\" width=\"50\"/>\n",
        "  </a>\n",
        "  <a href=\"https://devicon.dev/\">\n",
        "    <img src=\"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg\" width=\"50\" />\n",
        "  </a>\n",
        "</p>\n",
        "\n",
        "## 🎯 Objetivos\n",
        "\n",
        "- Estimular o trabalho em equipe.\n",
        "- Compartilhar o conhecimento com colegas, por meio da troca de experiências, ajuda e dúvidas.\n",
        "- Criar um portfólio profissional colaborativo.\n",
        "- Praticar habilidades em HTML, CSS e versionamento com GIT e GITHUB.\n",
        "\n",
        "## 👩‍💻 Sobre mim\n",
        "\n",
        "Oi, me chamo Railane, e atualmente estou em cursos da Embarcados e desenvolvimento full stack, com isso e um pouco mais, pretendo investir em projetos que envolvem causas sociais e ambientais.\n",
        "\n",
        "- 💻 Interesses: Progamação de sistemas, programação e montagem de robôs.\n",
        "- 📚 Estudando atualmente: Python, Java, Firmware\n",
        "- 📫 Contato: [railanemesquita34@gmail.com]\n",
        "\n",
        "## 🛠️ Principais Comandos GIT utilizados\n",
        "\n",
        "| Comando                | Função                                         |\n",
        "|------------------------|------------------------------------------------|\n",
        "| git init               | Cria um repositório Git local.                |\n",
        "| git add .              | Adiciona todos os arquivos alterados.         |\n",
        "| git commit -m \"msg\"    | Salva as alterações com uma mensagem.         |\n",
        "| git push               | Envia os commits para o GitHub.               |\n",
        "| git pull               | Baixa atualizações do GitHub.                 |\n",
        "| git status             | Mostra os arquivos modificados.               |\n",
        "| git log                | Lista os commits realizados.                  |"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "XSvM6NWjMDdu"
      },
      "source": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "MUWUFNkunAqz",
        "vscode": {
          "languageId": "html"
        }
      },
      "outputs": [],
      "source": [
        "<!DOCTYPE html>\n",
        "<html lang=\"en\">\n",
        "<head>\n",
        "  <meta charset=\"UTF-8\" />\n",
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n",
        "  <link rel=\"stylesheet\" href=\"style.css\" />\n",
        "  <title>Portfólio</title>\n",
        "\n",
        "</head>\n",
        "<body>\n",
        "\n",
        "  <header></header>\n",
        "\n",
        "  <main>\n",
        "    <!-- Introdução -->\n",
        "    <div class=\"introducao\">\n",
        "      <div class=\"textoApresentacao\">\n",
        "        <h1 class=\"titulo\">Apresentação</h1>\n",
        "        <p class=\"paragrafo\">texto de apresentação*</p>\n",
        "      </div>\n",
        "      <img src=\"img/foto.jpg\" alt=\"foto\" />\n",
        "    </div>\n",
        "\n",
        "    <!-- Continuação -->\n",
        "    <div class=\"continuacao\">\n",
        "      <h1 class=\"titulo\">Histórico profissional/acadêmico</h1>\n",
        "      <p class=\"texto\">texto de apresentação*</p>\n",
        "\n",
        "      <h1 class=\"titulo\">Interesses e especialidades técnicas</h1>\n",
        "      <p class=\"texto\">texto de apresentação*</p>\n",
        "\n",
        "      <h1 class=\"titulo\">Contato e Redes Sociais</h1>\n",
        "      <p class=\"texto\">texto de apresentação*</p>\n",
        "    </div>\n",
        "\n",
        "    <!-- Barra de habilidades -->\n",
        "    <div class=\"skill\">\n",
        "      <span>Ferramenta</span>\n",
        "      <div class=\"progress-bar\">\n",
        "        <div class=\"progress\" style=\"width: 90%\"></div>\n",
        "      </div>\n",
        "    </div>\n",
        "    <div class=\"skill\">\n",
        "      <span>Ferramenta</span>\n",
        "      <div class=\"progress-bar\">\n",
        "        <div class=\"progress\" style=\"width: 90%\"></div>\n",
        "      </div>\n",
        "    </div>\n",
        "    <div class=\"skill\">\n",
        "      <span>Ferramenta</span>\n",
        "      <div class=\"progress-bar\">\n",
        "        <div class=\"progress\" style=\"width: 90%\"></div>\n",
        "      </div>\n",
        "    </div>\n",
        "\n",
        "    <!-- Interesses -->\n",
        "    <h2>Interesses</h2>\n",
        "    <div class=\"galeria\">\n",
        "      <img class=\"interesses\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfe5QANyfnkRMh6EQ6t95CWqBWe-52-UX54PViX_WslePsY2fJdghwuww&s=10\" alt=\"\" />\n",
        "      <img class=\"interesses\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfe5QANyfnkRMh6EQ6t95CWqBWe-52-UX54PViX_WslePsY2fJdghwuww&s=10\" alt=\"\" />\n",
        "      <img class=\"interesses\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfe5QANyfnkRMh6EQ6t95CWqBWe-52-UX54PViX_WslePsY2fJdghwuww&s=10\" alt=\"\" />\n",
        "      <img class=\"interesses\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfe5QANyfnkRMh6EQ6t95CWqBWe-52-UX54PViX_WslePsY2fJdghwuww&s=10\" alt=\"\" />\n",
        "      <img class=\"interesses\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfe5QANyfnkRMh6EQ6t95CWqBWe-52-UX54PViX_WslePsY2fJdghwuww&s=10\" alt=\"\" />\n",
        "      <img class=\"interesses\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfe5QANyfnkRMh6EQ6t95CWqBWe-52-UX54PViX_WslePsY2fJdghwuww&s=10\" alt=\"\" />\n",
        "      <img class=\"interesses\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfe5QANyfnkRMh6EQ6t95CWqBWe-52-UX54PViX_WslePsY2fJdghwuww&s=10\" alt=\"\" />\n",
        "      <img class=\"interesses\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfe5QANyfnkRMh6EQ6t95CWqBWe-52-UX54PViX_WslePsY2fJdghwuww&s=10\" alt=\"\" />\n",
        "      <img class=\"interesses\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfe5QANyfnkRMh6EQ6t95CWqBWe-52-UX54PViX_WslePsY2fJdghwuww&s=10\" alt=\"\" />\n",
        "      <img class=\"interesses\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfe5QANyfnkRMh6EQ6t95CWqBWe-52-UX54PViX_WslePsY2fJdghwuww&s=10\" alt=\"\" />\n",
        "      <img class=\"interesses\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfe5QANyfnkRMh6EQ6t95CWqBWe-52-UX54PViX_WslePsY2fJdghwuww&s=10\" alt=\"\" />\n",
        "    </div>\n",
        "\n",
        "  </main>\n",
        "\n",
        "  <footer></footer>\n",
        "\n",
        "</body>\n",
        "</html>\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "v-Lh1nmfMOVb",
        "vscode": {
          "languageId": "css"
        }
      },
      "outputs": [],
      "source": [
        "body{\n",
        "    background-color: black;\n",
        "    color: aliceblue;\n",
        "}\n",
        "\n",
        " .skill {\n",
        "      margin-bottom: 20px;\n",
        "    }\n",
        "    .progress-bar {\n",
        "      width: 50%;\n",
        "      height: 20px;\n",
        "      background-color: #e0e0e0;\n",
        "      border-radius: 10px;\n",
        "    }\n",
        "    .progress {\n",
        "      height: 100%;\n",
        "      background-color: #3498db;\n",
        "      border-radius: 10px;\n",
        "    }\n",
        "    .galeria {\n",
        "      border-style: double;\n",
        "      padding: 5%;\n",
        "      display: grid;\n",
        "      gap: 5%;\n",
        "      justify-content: center;\n",
        "      align-content: center;\n",
        "      grid-auto-flow: row;\n",
        "      grid-template-columns: repeat(4, auto);\n",
        "    }\n",
        "    .interesses {\n",
        "      width: 150px;\n",
        "      height: 150px;\n",
        "    }"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "vscode": {
          "languageId": "html"
        }
      },
      "outputs": [],
      "source": [
        "<!DOCTYPE html>\n",
        "<html lang=\"pt-BR\">\n",
        "    <head>\n",
        "        <meta charset=\"UTF-8\">\n",
        "        <meta name=\"viewport\" content=\"width=device-width, initial-scale-1.0\">\n",
        "        <title>Página de Contato</title>\n",
        "        <link rel=\"stylesheet\" href=\"style.css\">\n",
        "        <style>\n",
        "            body{\n",
        "                 font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;\n",
        "                 font-size: medium;\n",
        "                 background-color: #ffffff;\n",
        "                 margin: 0;\n",
        "                 padding: 20px;\n",
        "                 text-align: center;\n",
        "            }\n",
        "            .container{\n",
        "                     max-width: 600px;\n",
        "                     margin: auto;\n",
        "                     background: white;\n",
        "                     padding: 20px;\n",
        "                     border-radius: 5px;\n",
        "                     box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n",
        "            }            \n",
        "                \n",
        "\n",
        "            h1{\n",
        "            \n",
        "                text-align: center;\n",
        "                \n",
        "                \n",
        "            }\n",
        "            label{\n",
        "                \n",
        "                display: block;\n",
        "                margin: 10px 0 5px;\n",
        "                font-size: 20px;\n",
        "            }\n",
        "            input, textarea{\n",
        "                \n",
        "                width: 100%; \n",
        "                height: 50px; \n",
        "                resize: none;\n",
        "            }\n",
        "    \n",
        "            button{\n",
        "                background-color: blue;\n",
        "                color: #cec7c7;\n",
        "                border: none;\n",
        "                padding: 10px 15px;\n",
        "                border-radius: 4px;\n",
        "                cursor: pointer;\n",
        "                width: 100%;\n",
        "            }\n",
        "            button:hover{\n",
        "                background-color: rgb(46, 195, 61);\n",
        "            }\n",
        "\n",
        "        </style>\n",
        "    </head>\n",
        "    <body>\n",
        "        <div class=\"container\">\n",
        "        <h1>Página de Contato</h1>\n",
        "        <form action=\"malito:railanemesquita34@gmail.com\" method=\"post\" enctype=\"text/plain\"></form>\n",
        "    </form>\n",
        "    <a href=\"https://wa.me/5585981360256?text=fale%20comigo\" target=\"_blank\">\n",
        "        <img src=\"c:\\Users\\Samsung\\Downloads\\10000486.jpg\" alt=\"Envie-me mensagem no WhatsApp\" style=\"width: 40px;\">\n",
        "    </a>\n",
        "    <form action=\"mailto:railanemesquita342gmail.com\" method=\"post\" enctype=\"text/plain\">\n",
        "\n",
        "         <p><label for=\"Nome\">Nome:</label></p>\n",
        "         <input type=\"text\" id=\"nome\" name=\"nome\" required>\n",
        "\n",
        "         <p><label for=\"email\">Endereço de email:</label></p>\n",
        "         <input type=\"email\" id=\"email\" name=\"email\" required>\n",
        "\n",
        "         <p><label for=\"assunto\">Motivo do assunto:</label></p>\n",
        "         <textarea id=\"assunto\" name=\"assunto\" rows=\"4\" required></textarea>\n",
        "\n",
        "         <p><label for=\"telefone\">Número de telefone:</label></p>\n",
        "         <input type=\"tel\" id=\"telefone\" name=\"telefone\" required>\n",
        "\n",
        "         <p><label for=\"mensagem\">Mensagem:</label></p>\n",
        "         <textarea id=\"mensagem\" name=\"mensagem\" rows=\"4\" required></textarea>\n",
        "\n",
        "         <p><button type=\"submit\">Enviar formulário</button></p>\n",
        "       </form>\n",
        "      </div>\n",
        "</body>\n",
        "</html>\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "vscode": {
          "languageId": "html"
        }
      },
      "outputs": [],
      "source": [
        "<!DOCTYPE html>\n",
        "<html>\n",
        "    <head>\n",
        "        <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\n",
        "        <title>5 & 6</title>\n",
        "        <style>\n",
        "            .skill {\n",
        "                margin-bottom: 20px;\n",
        "            }\n",
        "            .progress-bar {\n",
        "                width: 50%;\n",
        "                height: 20px;\n",
        "                background-color: #e0e0e0;\n",
        "                border-radius: 10px;\n",
        "            }\n",
        "            .progress {\n",
        "                height: 100%;\n",
        "                background-color: #3498db;\n",
        "                border-radius: 10px;\n",
        "            }\n",
        "            .galeria {\n",
        "                border-style: double;\n",
        "                padding: 5%;\n",
        "                display: grid;\n",
        "                gap: 5%;\n",
        "                justify-content: center;\n",
        "                align-content: center;\n",
        "                grid-auto-flow: row;\n",
        "                grid-template-columns: repeat(4, auto);\n",
        "            }\n",
        "            .interesses {\n",
        "                width: 150px;\n",
        "                height: 150px;\n",
        "            }\n",
        "        </style>\n",
        "    </head>\n",
        "    <body>\n",
        "        <div class=\"skill\"></div>\n",
        "            <span>Linguagens de programaçãoa</span>\n",
        "            <div class=\"progress-bar\">\n",
        "                <div class=\"progress\" style=\"width: 60%\"></div>\n",
        "            </div>\n",
        "        </div>\n",
        "        <div class=\"skill\"></div>\n",
        "            <span>Elétrica/hardware</span>\n",
        "            <div class=\"progress-bar\">\n",
        "                <div class=\"progress\" style=\"width: 90%\"></div>\n",
        "            </div>\n",
        "        <div class=\"skill\"></div>\n",
        "            <span>Software</span>\n",
        "            <div class=\"progress-bar\">\n",
        "                <div class=\"progress\" style=\"width: 50%\"></div>\n",
        "        </div>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "vscode": {
          "languageId": "html"
        }
      },
      "outputs": [],
      "source": [
        "<section id=\"depoimentos\">\n",
        "  <h2>Depoimentos</h2>\n",
        "  <p class=\"subtitulo\">Depoimentos</p>\n",
        "  \n",
        "  <div class=\"container\">\n",
        "  </div>\n",
        "</section>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "vscode": {
          "languageId": "css"
        }
      },
      "outputs": [],
      "source": [
        "#depoimentos {\n",
        "  padding: 4rem 1rem;\n",
        "  background-color: #f9f9f9;\n",
        "}\n",
        "\n",
        "#depoimentos h2 {\n",
        "  text-align: center;\n",
        "  font-size: 2rem;\n",
        "  margin-bottom: 0.5rem;\n",
        "  color: #222;\n",
        "}\n",
        "\n",
        "#depoimentos .subtitulo {\n",
        "  text-align: center;\n",
        "  margin-bottom: 2rem;\n",
        "  color: #777;\n",
        "  font-size: 1rem;\n",
        "}"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "vscode": {
          "languageId": "html"
        }
      },
      "outputs": [],
      "source": [
        " <h2>Interesses</h2>\n",
        "        <div class=\"galeria\">\n",
        "            <img class=\"interesses\" src=\"Imagem do WhatsApp de 2025-05-16 à(s) 19.53.25_88c71e16.jpg\"/>\n",
        "            <img class=\"interesses\" src=\"20250509_165334.png\"/>\n",
        "            <img class=\"interesses\" src=\"flower-garden-1008668_1280.webp\"/> \n",
        "            <img class=\"interesses\" src=\"Imagem do WhatsApp de 2025-05-16 à(s) 19.41.45_7d71baa.jpg\"/>\n",
        "    </body>\n",
        "</html>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "vscode": {
          "languageId": "html"
        }
      },
      "outputs": [],
      "source": [
        "<html>\n",
        "\n",
        "    <style>\n",
        "         body {\n",
        "             background-color: #cb9ce48d;\n",
        "         }\n",
        "         h3 {\n",
        "             color: #8142ab;\n",
        "             font-family:cursive; \n",
        "         }\n",
        "         p {\n",
        "             color: #200537dc;\n",
        "                font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif\n",
        "         }\n",
        "         ul {\n",
        "             list-style-type: none; color: rgba(128, 4, 4, 0.799);\n",
        "                font-family:cursive;\n",
        "         }\n",
        "     </style>\n",
        "            \n",
        "    \n",
        "        </section>\n",
        "        <section>\n",
        "            <h3>Aprendizado</h3>\n",
        "            <h4>Estudo atualmente html, python e java.</h4>\n",
        "         <ul> \n",
        "            <p><li>HTML</li></p>\n",
        "            <p>🖼️ É a estrutura básica de qualquer página da web:</p>\n",
        "<pre><code>&lt;header&gt;, &lt;section&gt;, &lt;article&gt; e &lt;footer&gt;</code></pre>\n",
        "\n",
        "<p>Exemplo:</p>\n",
        "<pre style=\"background: #2d2d2d; color: #f8f8f2; padding: 1rem; border-radius: 6px;\"><code>&lt;form aria-label=\"Formulário de Contato\"&gt;\n",
        "  &lt;label for=\"nome\"&gt;Nome:&lt;/label&gt;\n",
        "  &lt;input type=\"text\" id=\"nome\" name=\"nome\" required&gt;\n",
        "  \n",
        "  &lt;label for=\"email\"&gt;Email:&lt;/label&gt;\n",
        "  &lt;input type=\"email\" id=\"email\" name=\"email\" required&gt;\n",
        "\n",
        "  &lt;button type=\"submit\"&gt;Enviar&lt;/button&gt;\n",
        "&lt;/form&gt;\n",
        "</code></pre>\n",
        " <p>Exemplo 2:</p>\n",
        "  <pre style=\"background: #2d2d2d; color: #f8f8f2; padding: 1rem; border-radius: 6px;\">\n",
        "<code>&lt;!DOCTYPE html&gt;\n",
        "&lt;html lang=\"pt-br\"&gt;\n",
        "&lt;head&gt;\n",
        "  &lt;meta charset=\"UTF-8\"&gt;\n",
        "  &lt;title&gt;Minha Página&lt;/title&gt;\n",
        "&lt;/head&gt;\n",
        "&lt;body&gt;\n",
        "  &lt;h1&gt;Olá, mundo!&lt;/h1&gt;\n",
        "&lt;/body&gt;\n",
        "&lt;/html&gt;</code>\n",
        "  </pre>\n",
        "</form></p> <br><br>\n",
        "         \n",
        "        <p><li>Css</li></p> \n",
        "        <h3>🎨 Define a aparência e o layout das páginas da web:</h3>\n",
        "      <p>Exemplo:</p>\n",
        "       <pre style=\"background: #2d2d2d; color: #f8f8f2; padding: 1rem; border-radius: 6px;\"><code>\n",
        "p {\n",
        "  color: blue;\n",
        "  font-size: 16px;\n",
        "}\n",
        "</code></pre><br><br>\n",
        "\n",
        "        <p><li>Python</li></p>  \n",
        "        <h3>🐍 Pode Verificar se um número é par ou ímpar</h3>\n",
        "        <p>Exemplo:</p>\n",
        "  <pre style=\"background: #2d2d2d; color: #f8f8f2; padding: 1rem; border-radius: 6px;\">\n",
        "<code>numero = int(input(\"Digite um número: \"))\n",
        "if numero % 2 == 0:\n",
        "    print(\"É par.\")\n",
        "else:\n",
        "    print(\"É ímpar.\")</code>\n",
        "  </pre><br><br>\n",
        "  <p><li>Java</li></p>\n",
        "  <h3>Também pode dizer Ola mundo!, de uma maneira diferente</h3>\n",
        "<p>Exemplo</p>\n",
        "<pre style=\"background: #2d2d2d; color: #f8f8f2; padding: 1rem; border-radius: 6px;\">\n",
        "    <code>public class OlaMundo {\n",
        "    public static void main(String[] args) {\n",
        "        System.out.println(\"Olá, Mundo!\");\n",
        "    }\n",
        "}</code>\n",
        "</pre><br><br>\n",
        "\n",
        "    <h3>💬 Deixe seu comentário:</h3>\n",
        "  <form style=\"display: flex; flex-direction: column; max-width: 500px;\">\n",
        "    <label for=\"nome\">Nome:</label>\n",
        "    <input type=\"text\" id=\"nome\" name=\"nome\" placeholder=\"Digite seu nome\" required style=\"padding: 0.5rem; margin-bottom: 1rem;\">\n",
        "\n",
        "    <label for=\"comentario\">Comentário:</label>\n",
        "    <textarea id=\"comentario\" name=\"comentario\" rows=\"4\" placeholder=\"Escreva aqui seu comentário\" required style=\"padding: 0.5rem; margin-bottom: 1rem;\"></textarea>\n",
        "\n",
        "    <button type=\"submit\" style=\"background-color: #4caf50; color: white; padding: 0.7rem; border: none; border-radius: 4px; cursor: pointer;\">\n",
        "      Enviar\n",
        "    </button>\n",
        "  </form>\n",
        "  </body>\n",
        "</html>"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
